"""add rh_documents and rh_folders tables

Revision ID: b870387316c8
Revises: 
Create Date: 2025-10-06 19:57:04.472140

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b870387316c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_permissions')
    op.drop_table('rh_document')
    with op.batch_alter_table('rh_folder', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('name'))

    op.drop_table('rh_folder')
    with op.batch_alter_table('rh_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), nullable=True))
        batch_op.alter_column('file_path',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.alter_column('file_type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('file_size',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('folder_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('uploaded_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.drop_column('title')
        batch_op.drop_column('is_public')
        batch_op.drop_column('version')
        batch_op.drop_column('file_name')

    with op.batch_alter_table('rh_folders', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('created_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('rh_folders_ibfk_1'), type_='foreignkey')
        batch_op.drop_column('parent_id')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rh_folders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('parent_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('rh_folders_ibfk_1'), 'rh_folders', ['parent_id'], ['id'])
        batch_op.alter_column('created_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=False)

    with op.batch_alter_table('rh_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_name', mysql.VARCHAR(length=500), nullable=False))
        batch_op.add_column(sa.Column('version', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('is_public', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('title', mysql.VARCHAR(length=300), nullable=False))
        batch_op.alter_column('uploaded_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('folder_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('file_size',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('file_type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('file_path',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=False)
        batch_op.drop_column('is_archived')
        batch_op.drop_column('name')

    op.create_table('rh_folder',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('rh_folder', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('name'), ['name'], unique=True)

    op.create_table('rh_document',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('size', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('downloads', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('folder_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('uploaded_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['rh_folder.id'], name=op.f('rh_document_ibfk_1')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], name=op.f('rh_document_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('document_permissions',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('document_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('folder_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('permission_type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['rh_documents.id'], name=op.f('document_permissions_ibfk_1')),
    sa.ForeignKeyConstraint(['folder_id'], ['rh_folders.id'], name=op.f('document_permissions_ibfk_2')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('document_permissions_ibfk_3')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
