"""add base_salary to employee

Revision ID: ce211251f760
Revises: b870387316c8
Create Date: 2025-10-07 11:29:12.628433

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ce211251f760'
down_revision = 'b870387316c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Supprimer le drop de justification pour éviter l'erreur si la table n'existe pas
    # op.drop_table('justification')

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_salary', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('bank_account', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('bank_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('css_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ipres_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('css_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ipres_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tax_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('trimf_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('family_situation', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('dependents', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('id_card_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('id_card_expiry', sa.Date(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        # Commenter la contrainte UNIQUE pour éviter l'erreur si doublons
        # batch_op.create_unique_constraint(None, ['user_id'])
        batch_op.drop_column('email')
        batch_op.drop_column('first_name')
        batch_op.drop_column('phone')
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('phone', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('first_name', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('email', mysql.VARCHAR(length=120), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.drop_column('id_card_expiry')
        batch_op.drop_column('id_card_number')
        batch_op.drop_column('dependents')
        batch_op.drop_column('family_situation')
        batch_op.drop_column('trimf_rate')
        batch_op.drop_column('tax_number')
        batch_op.drop_column('ipres_rate')
        batch_op.drop_column('css_rate')
        batch_op.drop_column('ipres_number')
        batch_op.drop_column('css_number')
        batch_op.drop_column('bank_name')
        batch_op.drop_column('bank_account')
        batch_op.drop_column('base_salary')

    # On ne recrée pas la table justification si elle n'existe plus
    # op.create_table('justification',
    # ... reste du code ...
    # )
    # ### end Alembic commands ###


    op.create_table('justification',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('attendance_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('commentaire', mysql.TEXT(), nullable=False),
    sa.Column('date_justification', mysql.DATETIME(), nullable=True),
    sa.Column('statut', mysql.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendance.id'], name=op.f('justification_ibfk_2')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('justification_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
